[build]
command = "npm run build"
publish = "public"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true"

# Cache node_modules between builds
[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "frame-ancestors 'self' *.youcanbook.me *.ycb.me; frame-src 'self' *.youcanbook.me *.ycb.me https:;"

[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
from = "https://www.vriendenaantafel.be/*"
to = "https://www.komaantafel.be/:splat"
status = 301
force = true
